title: K-POP bias sorter
author: "@nelsonkct"
description: >-
  Choose your favOriTe member in each battle to get an accurate K-POP idol ranking.
baseurl: "/KPOP_Bias_Sorter"
url: "https://nelsonkct.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from site build
exclude:
  - .DS_Store
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .bundle/