title: K-pop bias sorter
author: "@nelsonkct"
description: >-
  Choose your favorite member in each battle to get an accurate K-pop ranking. Featuring IVE, aespa, (G)I-DLE, Red Velvet, and ITZY.
baseurl: "/KPOP_Bias_Sorter"
url: "https://nelsonkct.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from site build
exclude:
  - .DS_Store
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .bundle/